const assImages = {
  Avatar: require("./Avatar/shopeefood.png"),
  flagVn: require("./Avatar/flagVN.png"),
  mainBanner: require("./Avatar/main-banner.jpg"),
  AppStore: require("./Avatar/app-store.png"),
  CHplay: require("./Avatar/CH-play.png"),
  // listFoodOne: require("./Avatar/food.jpeg"),
  // listFoodTow: require("./Avatar/foodtow.jpg"),
  listFoodThree: require("./Avatar/partner2x.png"),
  Screenshot1: require("./Avatar/Screenshot1.png"),
  Screenshot2: require("./Avatar/Screenshot2.png"),
  Preservation: require("./Avatar/Preservation-footer.png"),
  PhoneReg: require("./Avatar/Phone-reg.png"),
  bgDeliverynow: require("./Avatar/bg-deliverynow.png"),
  HuaweiVn: require("./Avatar/Huawei-vn.png"),
  LogoShopeefoodVN: require("./Avatar/Logo-ShopeefoodVN.png"),
  govSeals1: require("./Avatar/gov_seals1.jpg"),
  AppStoreVn: require("./Avatar/AppStore-vn.png"),
  PlayStoreVn: require("./Avatar/PlayStore-vn.png"),
  Shipper: require("./Avatar/Shipper.png"),
  ENGLIS: require("./Avatar/ENGLIS.png"),
  bgSearch: require("./Avatar/bg-search.png"),
  bunBo: require("./Avatar/bonbo.jpg"),
  partnerVi: require("./Avatar/partner-vi.png"),
  qrcode: require("./Avatar/qrcode.png"),
  shopeefoodCart: require("./Avatar/shopeefood-cart.png"),
  // foodProduct: require("./Avatar/food-product.jpeg"),
  shopeefoodUser: require("./Avatar/shopeefoodUser.png"),
  store_grub: require("./Avatar/store_grub.webp"),
  priceWebp: require("./Avatar/price-right.webp"),
  Zalo_pay: require("./Avatar/Zalo_pay.webp"),
  userAdmin: require("./Avatar/userAdmin.jpg"),
};
export default assImages;
